### PR TITLE
Replace calls to DataValue::getTitle() by DataItem::getTitle()

### LINKED ISSUE #493: Tests are failing due to "Call to private method ..."
### Setup

Multiple setups.

### Issue

[Tests fail](https://travis-ci.org/SemanticMediaWiki/SemanticResultFormats/jobs/533737613) with for following errors, i.e. either calls to private method `SMWWikiPageValue::getSortKey()` or `SMWWikiPageValue::getTitle()`:

- Error: Call to private method `SMWWikiPageValue::getSortKey()` from context 'SRF\Filtered\ResultItem' 2x
- Error: Call to private method `SMWWikiPageValue::getTitle()` from context 'SRF\Gallery'
- Error: Call to private method `SMWWikiPageValue::getTitle()` from context 'SRF\iCalendar\iCalendarFileExportPrinter'
- Error: Call to private method `SMWWikiPageValue::getTitle()` from context 'SRF\iCalendar\iCalendarFileExportPrinter' 2x
- Error: Call to private method `SMWWikiPageValue::getTitle()` from context 'SRF\TagCloud'
- Error: Call to private method `SMWWikiPageValue::getTitle()` from context 'SRFTimeline'

### PR DESCRIPTION
**Pull request by s7eph4n**
This PR is made in reference to: #493

This PR replaces calls to DataValue::getTitle() by calls to DataItem::getTitle():
-	modified:   formats/dygraphs/SRF_Dygraphs.php
-	modified:   formats/filtered/src/ResultItem.php
-	modified:   formats/filtered/src/View/CalendarView.php
-	modified:   formats/gallery/Gallery.php
-	modified:   formats/media/MediaPlayer.php
-	modified:   formats/slideshow/SRF_SlideShow.php
-	modified:   formats/tagcloud/TagCloud.php
-	modified:   formats/timeline/SRF_Timeline.php
-	modified:   formats/valuerank/SRF_ValueRank.php
-	modified:   src/iCalendar/iCalendarFileExportPrinter.php
-	modified:   src/vCard/vCardFileExportPrinter.php

This PR includes:
- [ ] Update of RELEASE-NOTES.md
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes #493

### CODE REVIEW

**Comment by s7eph4n** [comment]
(Failed tests are unrelated.)

Not all formats have tests and I did not create them for this. Would be great if somebody could review the patch.

File: formats/dygraphs/SRF_Dygraphs.php [hunk 1]
```diff
@@ -90,27 +90,29 @@ protected function getResultData( SMWQueryResult $result, $outputMode ) {
 				while ( ( $dataValue = $field->getNextDataValue() ) !== false ) { // Data values
 
 					// Jump the column (indicated by continue) because we don't want the data source being part of the annotation array
-					if ( $dataValue->getDataItem()->getDIType(
-						) == SMWDataItem::TYPE_WIKIPAGE && $this->params['datasource'] === 'raw' && !$dataSource ) {
+					$dataItem = $dataValue->getDataItem();
+
+					if ( $dataItem->getDIType() === SMWDataItem::TYPE_WIKIPAGE ) {
+						$title = $dataItem->getTitle();
+					}
```
Comment (JeroenDeDauw) [inline formats/dygraphs/SRF_Dygraphs.php]: This is a bit scary... $title might end up not being defined or still be from the previous iteration. Probably need to extract some functions to make this code not scary.

**Comment by JeroenDeDauw** [comment]
Thanks @s7eph4n !
